input.onPinPressed(TouchPin.P0, function () {
    basic.pause(100)
    basic.showString("DONT RUN")
    basic.showIcon(IconNames.No)
    basic.pause(5000)
    basic.clearScreen()
    basic.showString("NO CORRA")
    basic.showIcon(IconNames.No)
    basic.pause(5000)
    basic.clearScreen()
})
input.onButtonPressed(Button.A, function () {
    basic.pause(100)
    basic.showString("ENTRY")
    basic.showArrow(ArrowNames.North)
    basic.pause(5000)
    basic.clearScreen()
    basic.showString("ENTRADA")
    basic.showArrow(ArrowNames.North)
    basic.pause(5000)
    basic.clearScreen()
})
input.onPinPressed(TouchPin.P2, function () {
    basic.pause(100)
    basic.showString("MUCHAS GRACIAS ")
    basic.pause(1000)
    basic.showString("POR SU ATENCION ")
    basic.pause(100)
    music.playMelody("E D G F B A C5 B ", 120)
    basic.showIcon(IconNames.SmallHeart)
    basic.pause(75)
    basic.showIcon(IconNames.Heart)
    basic.pause(75)
    basic.showIcon(IconNames.SmallHeart)
    basic.pause(75)
    basic.showIcon(IconNames.Heart)
})
input.onButtonPressed(Button.B, function () {
    basic.pause(100)
    basic.showString("EXIT")
    basic.showArrow(ArrowNames.East)
    basic.pause(5000)
    basic.clearScreen()
    basic.showString("SALIDA")
    basic.showArrow(ArrowNames.East)
    basic.pause(5000)
    basic.clearScreen()
})
input.onPinPressed(TouchPin.P1, function () {
    basic.pause(100)
    basic.showString("WALK")
    basic.showIcon(IconNames.Yes)
    basic.pause(5000)
    basic.clearScreen()
    basic.showString("CAMINE")
    basic.showIcon(IconNames.Yes)
    basic.pause(5000)
    basic.clearScreen()
})
music.startMelody(music.builtInMelody(Melodies.Prelude), MelodyOptions.ForeverInBackground)
basic.pause(100)
basic.showString("BIENVENIDOS ")
basic.pause(100)
basic.showString("MI NOMBRE ES ANDREA DE")
basic.showNumber(11)
music.stopMelody(MelodyStopOptions.All)
